#
# Generated by erpcgen 1.7.4 on Thu Jun  3 17:44:56 2021.
#
# AUTOGENERATED - DO NOT EDIT
#

import erpc

# Abstract base class for BLEmesh_api
class IBLEmesh_api(object):
    SERVICE_ID = 3
    MESH_INIT_ID = 1
    BT_MESH_INIT_PROV_RAW_INIT_ID = 2
    BT_MESH_INIT_COMP_RAW_INIT_ID = 3
    BT_MESH_INIT_ELEM_RAW_INIT_ID = 4
    BT_MESH_CFG_CLI_RAW_INIT_ID = 5
    BT_MESH_INIT_MODEL_RAW_INIT_ID = 6
    BT_MESH_CFG_SRV_RAW_INIT_ID = 7
    BT_MESH_HEALTH_SRV_RAW_INIT_ID = 8
    BT_MESH_RESET_ID = 9
    BT_MESH_SUSPEND_ID = 10
    BT_MESH_RESUME_ID = 11
    BT_MESH_IV_UPDATE_TEST_ID = 12
    BT_MESH_IV_UPDATE_ID = 13
    BT_MESH_LPN_SET_ID = 14
    BT_MESH_LPN_POLL_ID = 15
    BT_MESH_INPUT_STRING_ID = 16
    BT_MESH_INPUT_NUMBER_ID = 17
    BT_MESH_PROV_ENABLE_WRAPPER_ID = 18
    BT_MESH_PROV_DISABLE_WRAPPER_ID = 19
    BT_MESH_PROVISION_ID = 20
    BT_MESH_CFG_APP_KEY_ADD_WRAPPER_ID = 21
    BT_MESH_CFG_MOD_APP_BIND_VND_WRAPPER_ID = 22
    BT_MESH_CFG_MOD_APP_BIND_WRAPPER_ID = 23
    BT_MESH_CFG_MOD_SUB_ADD_VND_WRAPPER_ID = 24
    BT_MESH_CFG_MOD_SUB_ADD_WRAPPER_ID = 25
    BT_MESH_CFG_MOD_SUB_DEL_WRAPPER_ID = 26
    BT_MESH_CFG_MOD_SUB_DEL_VND_WRAPPER_ID = 27
    BT_MESH_CFG_MOD_SUB_VA_ADD_WRAPPER_ID = 28
    BT_MESH_CFG_MOD_SUB_VA_ADD_VND_WRAPPER_ID = 29
    BT_MESH_CFG_MOD_PUB_SET_WRAPPER_ID = 30
    BT_MESH_CFG_MOD_PUB_SET_VND_WRAPPER_ID = 31
    BT_MESH_IS_PROVISIONED_ID = 32
    BT_MESH_PROXY_IDENTITY_ENABLE_ID = 33
    BT_MESH_MODEL_PUBLISH_WRAPPER_ID = 34
    BT_MESH_MODEL_SEND_DATA_WRAPPER_ID = 35
    BT_MESH_MODEL_FIND_WRAPPER_ID = 36
    BT_MESH_MODEL_FIND_VND_WRAPPER_ID = 37
    BT_MESH_MODEL_EXTEND_WRAPPER_ID = 38
    BT_MESH_FAULT_UPDATE_WRAPPER_ID = 39
    SETTINGS_LOAD_WRAPPER_ID = 40
    STORE_DATA_WRAPPER_ID = 41

    def mesh_init(self):
        raise NotImplementedError()

    def bt_mesh_init_prov_raw_init(self, prov_raw):
        raise NotImplementedError()

    def bt_mesh_init_comp_raw_init(self, comp_raw):
        raise NotImplementedError()

    def bt_mesh_init_elem_raw_init(self, elem_index, elem_raw):
        raise NotImplementedError()

    def bt_mesh_cfg_cli_raw_init(self, elem_index, model_index):
        raise NotImplementedError()

    def bt_mesh_init_model_raw_init(self, elem_index, model_index, model_raw, op_raw):
        raise NotImplementedError()

    def bt_mesh_cfg_srv_raw_init(self, elem_index):
        raise NotImplementedError()

    def bt_mesh_health_srv_raw_init(self, elem_index, model_index, health_srv, max_faults):
        raise NotImplementedError()

    def bt_mesh_reset(self):
        raise NotImplementedError()

    def bt_mesh_suspend(self):
        raise NotImplementedError()

    def bt_mesh_resume(self):
        raise NotImplementedError()

    def bt_mesh_iv_update_test(self, enable):
        raise NotImplementedError()

    def bt_mesh_iv_update(self):
        raise NotImplementedError()

    def bt_mesh_lpn_set(self, enable):
        raise NotImplementedError()

    def bt_mesh_lpn_poll(self):
        raise NotImplementedError()

    def bt_mesh_input_string(self, str):
        raise NotImplementedError()

    def bt_mesh_input_number(self, num):
        raise NotImplementedError()

    def bt_mesh_prov_enable_wrapper(self, bearers):
        raise NotImplementedError()

    def bt_mesh_prov_disable_wrapper(self, bearers):
        raise NotImplementedError()

    def bt_mesh_provision(self, net_key, net_idx, flags, iv_index, addr, dev_key):
        raise NotImplementedError()

    def bt_mesh_cfg_app_key_add_wrapper(self, net_idx, addr, key_net_idx, key_app_idx, app_key):
        raise NotImplementedError()

    def bt_mesh_cfg_mod_app_bind_vnd_wrapper(self, net_idx, addr, elem_addr, mod_app_idx, mod_id, cid):
        raise NotImplementedError()

    def bt_mesh_cfg_mod_app_bind_wrapper(self, net_idx, addr, elem_addr, mod_app_idx, mod_id):
        raise NotImplementedError()

    def bt_mesh_cfg_mod_sub_add_vnd_wrapper(self, net_idx, addr, elem_addr, sub_addr, mod_id, cid):
        raise NotImplementedError()

    def bt_mesh_cfg_mod_sub_add_wrapper(self, net_idx, addr, elem_addr, sub_addr, mod_id):
        raise NotImplementedError()

    def bt_mesh_cfg_mod_sub_del_wrapper(self, net_idx, addr, elem_addr, sub_addr, mod_id):
        raise NotImplementedError()

    def bt_mesh_cfg_mod_sub_del_vnd_wrapper(self, net_idx, addr, elem_addr, sub_addr, mod_id, cid):
        raise NotImplementedError()

    def bt_mesh_cfg_mod_sub_va_add_wrapper(self, net_idx, addr, elem_addr, label, mod_id):
        raise NotImplementedError()

    def bt_mesh_cfg_mod_sub_va_add_vnd_wrapper(self, net_idx, addr, elem_addr, label, mod_id, cid):
        raise NotImplementedError()

    def bt_mesh_cfg_mod_pub_set_wrapper(self, net_idx, addr, elem_addr, mod_id, pub):
        raise NotImplementedError()

    def bt_mesh_cfg_mod_pub_set_vnd_wrapper(self, net_idx, addr, elem_addr, mod_id, cid, pub):
        raise NotImplementedError()

    def bt_mesh_is_provisioned(self):
        raise NotImplementedError()

    def bt_mesh_proxy_identity_enable(self):
        raise NotImplementedError()

    def bt_mesh_model_publish_wrapper(self, elem_idx, is_vnd, model_index, msg):
        raise NotImplementedError()

    def bt_mesh_model_send_data_wrapper(self, elem_idx, is_vnd, model_index, ctx, msg):
        raise NotImplementedError()

    def bt_mesh_model_find_wrapper(self, elem_idx, id):
        raise NotImplementedError()

    def bt_mesh_model_find_vnd_wrapper(self, elem_idx, company, id):
        raise NotImplementedError()

    def bt_mesh_model_extend_wrapper(self, mod_elem_idx, mod_is_vnd, mod_idx, base_mod_elem_idx, base_mod_is_vnd, base_mod_idx):
        raise NotImplementedError()

    def bt_mesh_fault_update_wrapper(self, elem_idx):
        raise NotImplementedError()

    def settings_load_wrapper(self):
        raise NotImplementedError()

    def store_data_wrapper(self, elem_index, is_vnd, model_index, name, data):
        raise NotImplementedError()


